title: "DLS Handbook"
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: true
aux_links:
  "DLS Handbook on GitHub":
    - "//github.com/pulibrary/dls-handbook"
aux_links_new_tab: true
